logging:
  backup_count: 5
  console_output: true
  format: structured
  level: INFO
  log_to_file: true
  max_file_size: 10485760
network:
  default_ports: 22,80,443,8080,8443
  default_timeout: 60
  dns_servers:
  - 8.8.8.8
  - 1.1.1.1
  max_concurrent_scans: 20
  ping_timeout: 3
output:
  auto_cleanup_days: 30
  create_directories: true
  default_format: json
  max_file_size: 104857600
  results_dir: results
  save_raw_output: true
  timestamp_format: '%Y%m%d-%H%M%S'
security:
  authorized_targets_only: true
  max_scan_depth: 3
  max_targets_per_scan: 100
  rate_limit_delay: 0.1
  require_authorization: true
  respect_robots_txt: true
  safe_mode: false
web:
  custom_headers: {}
  max_redirects: 5
  request_timeout: 15
  user_agent: BRS-RECON/0.0.2
  verify_ssl: false
